childBlocks: null
description: ''
enabled: true
field: 995cc5a8-988f-47f0-ac78-76d6b68f6ac6 # Blocks
fieldLayouts:
  09a4cffb-0928-4938-a6a0-0ac60754dd9e:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 58526062-22d5-4fc9-8ab0-24030f1db974 # Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6b4b01a1-5074-4a6e-a318-b9d5dcadde36
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7a500fed-1e75-478c-864b-4fc83c7574c7
        userCondition: null
group: null
handle: child
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: Child
sortOrder: 2
topLevel: false
