dateModified: 1670514449
elementSources:
  craft\elements\Entry:
    -
      disabled: false
      key: '*'
      tableAttributes:
        - section
        - postDate
        - expiryDate
        - author
        - link
      type: native
    -
      key: singles
      type: native
    -
      key: 'section:1f4732b0-84b4-4302-9a0f-687b30fdd6a0'
      type: native
    -
      heading: ''
      type: heading
    -
      key: 'section:d630234c-e5b7-4e5c-a00b-62c58a09595c'
      type: native
    -
      key: 'section:04d5a0fa-7712-4c14-80b1-499740922557'
      type: native
email:
  fromEmail: $SYSTEM_EMAIL_ADDRESS
  fromName: $SYSTEM_EMAIL_ADDRESS
  replyToEmail: null
  template: ''
  transportSettings:
    command: ''
  transportType: craft\mail\transportadapters\Sendmail
fs:
  public:
    hasUrls: true
    name: Public
    settings:
      path: '@webroot/assets'
    type: craft\fs\Local
    url: /assets/
meta:
  __names__:
    1cf7995f-6f4d-4f3d-ae1b-725d7d2dacd0: 'Menu Item' # Menu Item
    3dc3f5a1-bcf9-4805-9a54-f5dda1ad45a9: $PRIMARY_SITE_NAME # $PRIMARY_SITE_NAME
    5be54c1c-ac69-43da-bb71-a1a6d019ce48: Defaults # Defaults
    7e56e437-1c93-46fe-8cdd-77c67ee0edf1: Details # Details
    8c2efa0e-94d5-4d7d-86fc-b0af9e8d6f2c: Heading # Heading
    9d256421-0632-483e-ab16-fe4449e04977: Home # Home
    9fad34b4-ec00-4f1c-851e-7f96f31d86cf: Position # Position
    38b79782-e200-468f-9633-323021ffa8ca: Common # Common
    39e1484c-3c1a-4d64-a2e0-ff13cccb2890: 'Public Schema' # Public Schema
    45e98e00-01d3-4272-aa08-0b1227d51b81: 'Background Image' # Background Image
    78d3d90c-61e4-4555-b7a4-556ac5117ad2: Details # Details
    093b3471-f8ec-409f-92ce-54c068bbcbb2: Footer # Footer
    479b628a-5c5c-4ae8-a858-b5cd1b500c20: Button # Button
    995cc5a8-988f-47f0-ac78-76d6b68f6ac6: Blocks # Blocks
    1721cab1-b289-4a13-9143-1a55e53f453d: $PRIMARY_SITE_NAME # $PRIMARY_SITE_NAME
    093484b2-ab15-45dc-bddf-d693ba866b3d: Code # Code
    3512190e-891a-4d0b-8849-52dcc47d3fc6: Foobar # Foobar
    50013135-72e9-4dd1-965e-424db1bb07b8: 'Main Menu' # Main Menu
    58526062-22d5-4fc9-8ab0-24030f1db974: Text # Text
    95120525-750b-474d-891b-1f978c36a91a: Child # Child
    abf8e78e-1b0c-422c-bbff-9c89770e9906: Complex # Complex
    bdaf0b53-486b-46c0-9216-faf3ecbbd941: Details # Details
    c5cdbc1b-1b04-45b2-a9d4-e9a17059a72d: Home # Home
    c7803b14-f9ca-4ea2-8adb-77d4730289de: Public # Public
    dd7a858b-aedd-4c3d-9443-d3dbaf10f931: 'Edit Header' # Edit Header
    ec7644f6-7285-429f-9185-28284f2532a4: Global # Global
    f0762453-42d0-461a-8def-75f38a087a6a: Header # Header
    f9c5d4a4-e78f-476b-bdb0-b2bdb6204568: Code # Code
    f93ba9ca-aed6-465b-871c-a518711b649c: Buttons # Buttons
plugins:
  element-api:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
  neo:
    edition: standard
    enabled: true
    licenseKey: GCD4I1HRGWEQ8BGNOTRGP4HU
    schemaVersion: 3.5.2
system:
  edition: pro
  live: true
  name: $PRIMARY_SITE_NAME
  retryDuration: null
  schemaVersion: 4.0.0.9
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  deactivateByDefault: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
